# Generated by Django 2.1 on 2019-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_pk', models.PositiveIntegerField()),
                ('com_class', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetectionPat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_name', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=50)),
                ('cve', models.CharField(max_length=50)),
                ('rule_rdate', models.DateField()),
                ('rule_udate', models.DateField()),
                ('pro_state', models.CharField(max_length=50)),
                ('equ_class', models.CharField(max_length=50)),
                ('etc_equ_class', models.CharField(max_length=50, null=True)),
                ('att_class', models.CharField(max_length=50)),
                ('etc_att_class', models.CharField(max_length=50, null=True)),
                ('att_type', models.CharField(max_length=50)),
                ('etc_att_type', models.CharField(max_length=50, null=True)),
                ('pat_analysis', models.TextField()),
                ('countermeasures', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RansomwarePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('document_n', models.PositiveIntegerField()),
                ('send_date', models.DateField(blank=True, null=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_ip', models.CharField(max_length=50)),
                ('detect_date', models.DateField()),
                ('path', models.CharField(max_length=100)),
                ('reply', models.CharField(choices=[('', 'test')], max_length=30)),
                ('file_name', models.CharField(max_length=100)),
                ('process_state', models.CharField(choices=[('', 'test')], max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
