# Generated by Django 2.1 on 2019-09-30 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_auto_20190930_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_pk', models.PositiveIntegerField()),
                ('com_class', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('', 'test')], max_length=100)),
                ('process_method', models.CharField(max_length=100)),
                ('process_method_etc', models.CharField(max_length=200)),
                ('occurr_date', models.DateTimeField()),
                ('process_state', models.CharField(choices=[('', 'test')], max_length=100)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('manager_e_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_e_depart', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_e_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_e_cphone', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_e_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('visible_m', models.BooleanField(blank=True, default=False, null=True, verbose_name='(정)')),
                ('visible_s', models.BooleanField(blank=True, default=False, null=True, verbose_name='(부)')),
                ('visible_e', models.BooleanField(blank=True, default=False, null=True, verbose_name='(기타)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionPat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_name', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=50)),
                ('cve', models.CharField(max_length=50)),
                ('rule_rdate', models.DateField()),
                ('rule_udate', models.DateField()),
                ('pro_state', models.CharField(max_length=50)),
                ('equ_class', models.CharField(max_length=50)),
                ('etc_equ_class', models.CharField(max_length=50, null=True)),
                ('att_class', models.CharField(max_length=50)),
                ('etc_att_class', models.CharField(max_length=50, null=True)),
                ('att_type', models.CharField(max_length=50)),
                ('etc_att_type', models.CharField(max_length=50, null=True)),
                ('pat_analysis', models.TextField()),
                ('countermeasures', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_n', models.PositiveIntegerField()),
                ('send_date', models.DateField(blank=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('process_state', models.CharField(choices=[('', 'test')], max_length=30)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='RansomwarePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_n', models.PositiveIntegerField()),
                ('send_date', models.DateField(blank=True, null=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_ip', models.CharField(max_length=50)),
                ('detect_date', models.DateField()),
                ('path', models.CharField(max_length=100)),
                ('reply', models.CharField(choices=[('', 'test')], max_length=30)),
                ('file_name', models.CharField(max_length=100)),
                ('process_state', models.CharField(choices=[('', 'test')], max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Weekness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekness', to='post.Outflow')),
            ],
        ),
    ]
