# Generated by Django 2.1 on 2019-09-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecord',
            name='division',
            field=models.CharField(choices=[('', '선택하세요'), ('네트워크 장애 통보', '네트워크 장애 통보'), ('방화벽 정책 설정 지원', '방화벽 정책 설정 지원'), ('IPS 정책 설정 지원', 'IPS 정책 설정 지원'), ('보안관제 기술지원', '보안관제 기술지원'), ('내부정보 기술지원', '내부정보 기술지원'), ('악성코드 기술지원', '악성코드 기술지원'), ('랜섬웨어 기술지원', '랜섬웨어 기술지원')], max_length=100),
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='process_method_etc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='process_state',
            field=models.CharField(choices=[('', '선택하세요'), ('처리중', '처리중'), ('처리완료', '처리완료')], max_length=100),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='process_state',
            field=models.CharField(choices=[('', '선택하세요'), ('처리중', '처리중'), ('처리완료', '처리완료')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ransomwarepost',
            name='process_state',
            field=models.CharField(choices=[('', '선택하세요'), ('처리중', '처리중'), ('처리완료', '처리완료')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ransomwarepost',
            name='reply',
            field=models.CharField(choices=[('', '선택하세요'), ('회신', '회신'), ('미회신', '미회신')], max_length=30),
        ),
    ]
