# Generated by Django 2.1 on 2019-09-23 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('document_n', models.PositiveIntegerField()),
                ('send_date', models.DateField()),
                ('url', models.CharField(max_length=200)),
                ('process_state', models.CharField(choices=[('', '선택하세요'), ('처리중', '처리중'), ('처리완료', '처리완료')], max_length=30)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weekness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Outflow')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ransomwarepost',
            name='process_state',
            field=models.CharField(choices=[('', '선택하세요'), ('처리중', '처리중'), ('처리완료', '처리완료')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ransomwarepost',
            name='reply',
            field=models.CharField(choices=[('', '선택하세요'), ('회신', '회신'), ('미회신', '미회신')], max_length=30),
        ),
    ]
