# Generated by Django 2.1 on 2019-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionpat',
            name='etc_att_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detectionpat',
            name='etc_att_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detectionpat',
            name='etc_equ_class',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
