# Generated by Django 2.1 on 2019-09-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190930_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionPat',
        ),
    ]
