# Generated by Django 2.1 on 2019-09-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190923_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
