# Generated by Django 2.1 on 2019-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_delete_detectionpat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100, verbose_name='탐지 패턴명')),
                ('risk', models.CharField(choices=[('', '선택하세요')], max_length=100)),
                ('cve', models.CharField(max_length=100)),
                ('rule_regist_date', models.DateField(blank=True, null=True)),
                ('process_state', models.CharField(choices=[('', '선택하세요'), ('처리중', '처리중'), ('처리완료', '처리완료')], max_length=100)),
                ('equipment_class', models.CharField(max_length=100)),
                ('equipment_etc', models.CharField(blank=True, max_length=200, null=True)),
                ('attack_class', models.CharField(max_length=100)),
                ('attack_class_etc', models.CharField(blank=True, max_length=200, null=True)),
                ('attack_type', models.CharField(max_length=100)),
                ('attack_type_etc', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('countermeasures', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
