# Generated by Django 2.1 on 2019-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_detectionpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSTune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('file1', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')),
                ('file2', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detectionpattern',
            name='risk',
            field=models.CharField(choices=[('', '선택하세요'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100),
        ),
    ]
