# Generated by Django 2.1 on 2019-10-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191001_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPSTune',
        ),
    ]
