# Generated by Django 2.1 on 2019-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_attendance_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
