# Generated by Django 2.1 on 2019-10-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20191004_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='event_report_etc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='response_type_etc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='detect_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='direction',
            field=models.CharField(choices=[('', '선택하세요'), ('외 -> 내', '외 -> 내'), ('내 -> 외', '내 -> 외'), ('내 -> 내', '내 -> 내')], max_length=100),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='product_name',
            field=models.CharField(choices=[('', '선택하세요'), ('TrusGuard', 'TrusGuard'), ('MF2', 'MF2'), ('FortiGate', 'FortiGate'), ('NXG', 'NXG'), ('Neobox', 'Neobox'), ('기타', '기타')], max_length=100),
        ),
    ]
