# Generated by Django 2.1 on 2019-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20191007_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='product_etc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
