# Generated by Django 2.1 on 2019-09-18 02:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbBeneficcom',
            fields=[
                ('bc_number', models.AutoField(primary_key=True, serialize=False)),
                ('bc_date', models.DateTimeField()),
                ('bc_cu_name', models.CharField(max_length=50)),
                ('bc_cu_namein', models.BooleanField()),
                ('bc_cu_cnumber', models.IntegerField()),
                ('bc_cu_rname', models.CharField(max_length=50)),
                ('bc_cu_remail', models.EmailField(max_length=254)),
                ('bc_cu_bnumber', models.IntegerField(unique=True)),
                ('bc_cu_comclass', models.CharField(max_length=50)),
                ('bc_cu_business', models.CharField(max_length=50)),
                ('bc_cu_path', models.CharField(max_length=50)),
                ('bc_cu_homepage', models.CharField(blank=True, max_length=150, null=True)),
                ('bc_cu_address', models.CharField(max_length=100)),
                ('bc_cu_iaddress', models.CharField(max_length=100)),
                ('bc_im_security', models.BooleanField()),
                ('bc_im_internal', models.BooleanField()),
                ('bc_im_virus', models.BooleanField()),
                ('bc_im_ransomware', models.BooleanField()),
                ('bc_ss_security', models.CharField(max_length=10)),
                ('bc_ss_internal', models.CharField(max_length=10)),
                ('bc_ss_virus', models.CharField(max_length=10)),
                ('bc_ss_ransomware', models.CharField(max_length=10)),
                ('bc_op_lmove', models.CharField(blank=True, max_length=10, null=True)),
                ('bc_op_lpartner', models.CharField(blank=True, max_length=10, null=True)),
                ('bc_op_closure', models.CharField(blank=True, max_length=10, null=True)),
                ('bc_op_defense', models.CharField(blank=True, max_length=10, null=True)),
                ('bc_op_etc', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_ma_name', models.CharField(blank=True, max_length=10, null=True)),
                ('bc_ma_circles', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_ma_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_ma_cphone', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_ma_email', models.EmailField(max_length=254)),
                ('bc_re_name', models.CharField(blank=True, max_length=10, null=True)),
                ('bc_re_circles', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_re_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_re_cphone', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_re_email', models.EmailField(max_length=254)),
                ('bc_ch_name', models.CharField(blank=True, max_length=10, null=True)),
                ('bc_ch_circles', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_ch_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_ch_cphone', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_ch_email', models.EmailField(max_length=254)),
                ('bc_sdate', models.IntegerField()),
                ('bc_etc', models.TextField(blank=True, null=True)),
                ('bc_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'tb_beneficcom',
            },
        ),
        migrations.CreateModel(
            name='TbInternal',
            fields=[
                ('in_number', models.AutoField(primary_key=True, serialize=False)),
                ('in_date', models.DateTimeField()),
                ('in_contract', models.CharField(max_length=50)),
                ('in_apply', models.IntegerField()),
                ('in_cdate', models.DateField()),
                ('in_ip', models.CharField(max_length=50)),
                ('in_tdate', models.DateField()),
                ('in_treason', models.CharField(blank=True, max_length=80, null=True)),
                ('in_etc', models.TextField(blank=True, null=True)),
                ('in_benumber', models.ForeignKey(db_column='in_benumber', on_delete=django.db.models.deletion.DO_NOTHING, to='main.TbBeneficcom')),
            ],
            options={
                'db_table': 'tb_internal',
            },
        ),
        migrations.CreateModel(
            name='TbRansom',
            fields=[
                ('ra_number', models.AutoField(primary_key=True, serialize=False)),
                ('ra_date', models.DateTimeField()),
                ('ra_contract', models.CharField(max_length=50)),
                ('ra_apply', models.IntegerField()),
                ('ra_cdate', models.DateField()),
                ('ra_tdate', models.DateField()),
                ('ra_treason', models.CharField(blank=True, max_length=80, null=True)),
                ('ra_etc', models.TextField(blank=True, null=True)),
                ('re_benumber', models.ForeignKey(db_column='re_benumber', on_delete=django.db.models.deletion.DO_NOTHING, to='main.TbBeneficcom')),
            ],
            options={
                'db_table': 'tb_ransom',
            },
        ),
        migrations.CreateModel(
            name='TbSecurity',
            fields=[
                ('se_number', models.AutoField(primary_key=True, serialize=False)),
                ('se_date', models.DateTimeField()),
                ('se_contract', models.CharField(max_length=50)),
                ('se_pblock', models.CharField(max_length=80)),
                ('se_serial', models.CharField(max_length=80)),
                ('se_sdate', models.DateField()),
                ('se_cdate', models.DateField()),
                ('se_edate', models.DateField()),
                ('se_tdate', models.DateField()),
                ('se_treason', models.CharField(blank=True, max_length=80, null=True)),
                ('se_firmware', models.CharField(max_length=50)),
                ('se_eqclass', models.CharField(max_length=50)),
                ('se_ownership', models.CharField(max_length=50)),
                ('se_access', models.CharField(max_length=50)),
                ('se_ipsrule', models.BooleanField()),
                ('se_syslog', models.BooleanField()),
                ('se_icmp', models.BooleanField()),
                ('se_snmp', models.BooleanField()),
                ('se_etc', models.TextField(blank=True, null=True)),
                ('se_benumber', models.ForeignKey(db_column='se_benumber', on_delete=django.db.models.deletion.DO_NOTHING, to='main.TbBeneficcom')),
            ],
            options={
                'db_table': 'tb_security',
            },
        ),
        migrations.CreateModel(
            name='TbVirus',
            fields=[
                ('vi_number', models.AutoField(primary_key=True, serialize=False)),
                ('vi_date', models.DateTimeField()),
                ('vi_contract', models.CharField(max_length=50)),
                ('vi_apply', models.IntegerField()),
                ('vi_cdate', models.DateField()),
                ('vi_tdate', models.DateField()),
                ('vi_treason', models.CharField(blank=True, max_length=80, null=True)),
                ('vi_etc', models.TextField(blank=True, null=True)),
                ('vi_benumber', models.ForeignKey(db_column='vi_benumber', on_delete=django.db.models.deletion.DO_NOTHING, to='main.TbBeneficcom')),
            ],
            options={
                'db_table': 'tb_virus',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('user_name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=255, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일자')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_joined',),
            },
        ),
    ]
