# Generated by Django 2.1 on 2019-09-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_name', models.CharField(max_length=100)),
                ('cu_tenant', models.BooleanField()),
                ('cu_cnumber', models.CharField(max_length=100)),
                ('cu_serstate_security', models.CharField(max_length=100)),
                ('cu_serstate_information', models.CharField(max_length=100)),
                ('cu_serstate_virus', models.CharField(max_length=100)),
                ('cu_serstate_ransomware', models.CharField(max_length=100)),
                ('cu_imastate_security', models.BooleanField()),
                ('cu_imastate_information', models.BooleanField()),
                ('cu_imastate_virus', models.BooleanField()),
                ('cu_imastate_ransomware', models.BooleanField()),
                ('cu_business', models.CharField(max_length=100)),
                ('cu_comclass', models.CharField(max_length=100)),
                ('cu_path', models.CharField(max_length=100)),
                ('cu_rname', models.CharField(max_length=100)),
                ('cu_remail', models.EmailField(max_length=100)),
                ('cu_homepage', models.CharField(max_length=100)),
                ('cu_bnumber', models.CharField(max_length=100)),
                ('cu_address', models.CharField(max_length=100)),
                ('cu_iaddress', models.CharField(max_length=100)),
                ('op_imove', models.CharField(max_length=100)),
                ('op_lpartner', models.CharField(max_length=100)),
                ('op_closer', models.CharField(max_length=100)),
                ('op_defense', models.CharField(max_length=100)),
                ('op_etc', models.CharField(max_length=100)),
                ('ma_name', models.CharField(max_length=100)),
                ('ma_circles', models.CharField(max_length=100)),
                ('ma_phone', models.CharField(max_length=100)),
                ('ma_cphone', models.CharField(max_length=100)),
                ('ma_email', models.EmailField(max_length=254)),
                ('re_name', models.CharField(max_length=100)),
                ('re_circles', models.CharField(max_length=100)),
                ('re_phone', models.CharField(max_length=100)),
                ('re_cphone', models.CharField(max_length=100)),
                ('re_email', models.EmailField(max_length=254)),
                ('ch_name', models.CharField(max_length=100)),
                ('ch_circles', models.CharField(max_length=100)),
                ('ch_phone', models.CharField(max_length=100)),
                ('ch_cphone', models.CharField(max_length=100)),
                ('ch_email', models.EmailField(max_length=254)),
                ('bc_sdate', models.DateField()),
                ('bc_etc', models.TextField()),
                ('bc_file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_contract', models.CharField(max_length=100)),
                ('in_apply', models.PositiveIntegerField()),
                ('in_cdate', models.DateField()),
                ('in_ip', models.TextField()),
                ('in_tdate', models.DateField()),
                ('in_treason', models.CharField(max_length=100)),
                ('in_etc', models.TextField()),
                ('beneficCom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BeneficCom')),
            ],
        ),
        migrations.CreateModel(
            name='Ransomware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_contract', models.CharField(max_length=100)),
                ('ra_apply', models.PositiveIntegerField()),
                ('ra_cdate', models.DateField()),
                ('ra_tdate', models.DateField()),
                ('ra_treason', models.CharField(max_length=100)),
                ('ra_etc', models.TextField()),
                ('beneficCom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BeneficCom')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_contract', models.CharField(max_length=100)),
                ('se_pblock', models.CharField(max_length=100)),
                ('se_sdate', models.DateField()),
                ('se_cdate', models.DateField()),
                ('se_serial', models.CharField(max_length=100)),
                ('se_edate', models.DateField()),
                ('se_firmware', models.CharField(max_length=100)),
                ('se_eqclass', models.CharField(max_length=100)),
                ('se_ownership', models.CharField(max_length=100)),
                ('se_access', models.CharField(max_length=100)),
                ('se_ips', models.CharField(max_length=100)),
                ('se_tdate', models.DateField()),
                ('se_treason', models.CharField(max_length=100)),
                ('se_etc', models.TextField()),
                ('beneficCom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BeneficCom')),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_contract', models.CharField(max_length=100)),
                ('vi_apply', models.PositiveIntegerField()),
                ('vi_cdate', models.DateField()),
                ('vi_tdate', models.DateField()),
                ('vi_treason', models.CharField(max_length=100)),
                ('vi_etc', models.TextField()),
                ('beneficCom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BeneficCom')),
            ],
        ),
    ]
