# Generated by Django 2.1 on 2019-09-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190928_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='block_permis',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('선차단', '선차단'), ('권고', '권고'), ('IPS 룰 차단', 'IPS 룰 차단')], max_length=50, null=True),
        ),
    ]
