# Generated by Django 2.1 on 2019-09-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190929_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='large_scale',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('직접입력(추가)', '직접입력(추가)'), ('(재)경기도경제과학진흥원', '(재)경기도경제과학진흥원'), ('(재)서울산업진흥원', '(재)서울산업진흥원'), ('한국기술벤처재단', '한국기술벤처재단'), ('경기과학기술대학교', '경기과학기술대학교'), ('경기콘텐츠진흥원', '경기콘텐츠진흥원'), ('고대_산학재단', '고대_산학재단'), ('대구디지털산업진흥원(ICT파크)', '대구디지털산업진흥원(ICT파크)'), ('대구디지털산업진흥원(IDEA허브)', '대구디지털산업진흥원(IDEA허브)'), ('대구디지털산업진흥원(글로벌게임센터)', '대구디지털산업진흥원(글로벌게임센터)'), ('대구디지털산업진흥원(스마트콘텐츠상용화지원센터)', '대구디지털산업진흥원(스마트콘텐츠상용화지원센터)'), ('대구디지털산업진흥원(청년ICT창업성장센터)', '대구디지털산업진흥원(청년ICT창업성장센터)'), ('대구테크노파크', '대구테크노파크'), ('동국대학교_산학협력단', '동국대학교_산학협력단'), ('르호봇창업보육센터', '르호봇창업보육센터'), ('삼송테크노밸리', '삼송테크노밸리'), ('수원시창업지원센터', '수원시창업지원센터'), ('신구대_창업보육센터', '신구대_창업보육센터'), ('연세대원주산학협력단', '연세대원주산학협력단'), ('용인송담대학교산학협력단', '용인송담대학교산학협력단'), ('울산정보보호지원센터', '울산정보보호지원센터'), ('울산정보산업진흥원', '울산정보산업진흥원'), ('청주대학교창업보육센터', '청주대학교창업보육센터'), ('충북보건과학대학교산학협력단', '충북보건과학대학교산학협력단'), ('한양대학교창업보육센터', '한양대학교창업보육센터')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='smart_factory',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('직접입력(추가)', '직접입력(추가)'), ('스마트공장', '스마트공장')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='block_permis',
            field=models.CharField(blank=True, choices=[('', '선택하세요')], max_length=50, null=True),
        ),
    ]
