# Generated by Django 2.1 on 2019-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190930_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_class',
            field=models.CharField(choices=[('', '선택하세요'), ('제조업(C)', '제조업(C)'), ('광업(B)', '광업(B)'), ('건설업(F)', '건설업(F)'), ('운수 및 창고업(H)', '운수 및 창고업(H)'), ('정보통신업(J)', '정보통신업(J)'), ('사업시설 관리, 사업 지원 및 임대 서비스업(N)', '사업시설 관리, 사업 지원 및 임대 서비스업(N)'), ('보건업 및 사회복지 서비스업(Q)', '보건업 및 사회복지 서비스업(Q)'), ('농업, 임업 및 어업(A)', '농업, 임업 및 어업(A)'), ('전기, 가스, 증기 및 공기조절 공급업(D)', '전기, 가스, 증기 및 공기조절 공급업(D)'), ('도매 및 소매업(G)', '도매 및 소매업(G)'), ('숙박 및 음식점업(I)', '숙박 및 음식점업(I)'), ('금융 및 보험업(K)', '금융 및 보험업(K)'), ('전문, 과학 및 기술 서비스업(M)', '전문, 과학 및 기술 서비스업(M)'), ('예술, 스포츠 및 여가관련 서비스업(R)', '예술, 스포츠 및 여가관련 서비스업(R)'), ('수도, 하수 및 폐기물 처리, 원료 재생업(E)', '수도, 하수 및 폐기물 처리, 원료 재생업(E)'), ('교육 서비스업(P)', '교육 서비스업(P)'), ('협회 및 단체, 수리 및 기타 개인 서비스업(S)', '협회 및 단체, 수리 및 기타 개인 서비스업(S)'), ('부동산업(L)', '부동산업(L)'), ('공공 행정, 국방 및 사회보장 행정(O)', '공공 행정, 국방 및 사회보장 행정(O)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('', '선택하세요'), ('법인', '법인'), ('개인', '개인'), ('직접입력', '직접입력')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_uptae',
            field=models.CharField(choices=[('', '선택하세요'), ('전기/전자', '전기/전자'), ('화학/섬유', '화학/섬유'), ('기계/소재', '기계/소재'), ('정보/통신', '정보/통신'), ('바이오/의료', '바이오/의료'), ('에너지자원', '에너지자원'), ('지식서비스', '지식서비스'), ('기타', '기타')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='closed_net',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('o', 'o'), ('x', 'x')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='defense_industry',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('방위산업체', '방위산업체'), ('방위산업협력기업', '방위산업협력기업')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='join_path',
            field=models.CharField(choices=[('', '선택하세요'), ('홈페이지 및 이메일 안내', '홈페이지 및 이메일 안내'), ('유선연락 및 방문', '유선연락 및 방문'), ('보안교육 및 컨설팅', '보안교육 및 컨설팅'), ('지인 및 기관 추천', '지인 및 기관 추천'), ('지식재산센터', '지식재산센터')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='large_scale',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('직접입력(추가)', '직접입력(추가)'), ('(재)경기도경제과학진흥원', '(재)경기도경제과학진흥원'), ('(재)서울산업진흥원', '(재)서울산업진흥원'), ('한국기술벤처재단', '한국기술벤처재단'), ('경기과학기술대학교', '경기과학기술대학교'), ('경기콘텐츠진흥원', '경기콘텐츠진흥원'), ('고대_산학재단', '고대_산학재단'), ('대구디지털산업진흥원(ICT파크)', '대구디지털산업진흥원(ICT파크)'), ('대구디지털산업진흥원(IDEA허브)', '대구디지털산업진흥원(IDEA허브)'), ('대구디지털산업진흥원(글로벌게임센터)', '대구디지털산업진흥원(글로벌게임센터)'), ('대구디지털산업진흥원(스마트콘텐츠상용화지원센터)', '대구디지털산업진흥원(스마트콘텐츠상용화지원센터)'), ('대구디지털산업진흥원(청년ICT창업성장센터)', '대구디지털산업진흥원(청년ICT창업성장센터)'), ('대구테크노파크', '대구테크노파크'), ('동국대학교_산학협력단', '동국대학교_산학협력단'), ('르호봇창업보육센터', '르호봇창업보육센터'), ('삼송테크노밸리', '삼송테크노밸리'), ('수원시창업지원센터', '수원시창업지원센터'), ('신구대_창업보육센터', '신구대_창업보육센터'), ('연세대원주산학협력단', '연세대원주산학협력단'), ('용인송담대학교산학협력단', '용인송담대학교산학협력단'), ('울산정보보호지원센터', '울산정보보호지원센터'), ('울산정보산업진흥원', '울산정보산업진흥원'), ('청주대학교창업보육센터', '청주대학교창업보육센터'), ('충북보건과학대학교산학협력단', '충북보건과학대학교산학협력단'), ('한양대학교창업보육센터', '한양대학교창업보육센터'), ('기타 : 대규모', '기타 : 대규모')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='major_partner',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('직접입력(추가)', '직접입력(추가)'), ('KT', 'KT'), ('대우조선해양', '대우조선해양'), ('삼성전자협력사', '삼성전자협력사'), ('삼영무역', '삼영무역'), ('세종텔레콤', '세종텔레콤'), ('실리콘웍스', '실리콘웍스'), ('포스코ICT', '포스코ICT'), ('포스코켐텍', '포스코켐텍'), ('풍산안강사업장', '풍산안강사업장'), ('한국항공우주산업', '한국항공우주산업'), ('현대기아자동차그룹', '현대기아자동차그룹'), ('현대자동차협력사', '현대자동차협력사')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='smart_factory',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('직접입력(추가)', '직접입력(추가)'), ('스마트공장', '스마트공장')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ss_internal',
            field=models.CharField(choices=[('', '선택하세요'), ('미사용', '미사용'), ('사용중', '사용중'), ('개통예정', '개통예정'), ('해지', '해지')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='ss_ransomware',
            field=models.CharField(choices=[('', '선택하세요'), ('미사용', '미사용'), ('사용중', '사용중'), ('개통예정', '개통예정'), ('해지', '해지')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='ss_security',
            field=models.CharField(choices=[('', '선택하세요'), ('미사용', '미사용'), ('사용중', '사용중'), ('개통예정', '개통예정'), ('해지', '해지')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='ss_virus',
            field=models.CharField(choices=[('', '선택하세요'), ('미사용', '미사용'), ('사용중', '사용중'), ('개통예정', '개통예정'), ('해지', '해지')], max_length=20),
        ),
        migrations.AlterField(
            model_name='internal',
            name='contract',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('1년 약정', '1년 약정'), ('2년 약정', '2년 약정'), ('3년 약정', '3년 약정'), ('4년 약정', '4년 약정'), ('5년 약정', '5년 약정')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ransomware',
            name='contract',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('1년 약정', '1년 약정'), ('2년 약정', '2년 약정'), ('3년 약정', '3년 약정'), ('4년 약정', '4년 약정'), ('5년 약정', '5년 약정')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='access_permis',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('admin', 'admin'), ('Read', 'Read'), ('R/W', 'R/W'), ('None', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='block_permis',
            field=models.CharField(blank=True, choices=[('', '선택하세요')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='contract',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('1년 약정', '1년 약정'), ('2년 약정', '2년 약정'), ('3년 약정', '3년 약정'), ('4년 약정', '4년 약정'), ('5년 약정', '5년 약정')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='equipment_class',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('UTM', 'UTM'), ('IPS', 'IPS'), ('DDoS', 'DDoS'), ('FW', 'FW')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='icmp',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('사용', '사용'), ('미사용', '미사용')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='ips_rule',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('사용', '사용'), ('미사용', '미사용')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='ownership',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('임대장비', '임대장비'), ('씨애너스장비', '씨애너스장비'), ('고객장비', '고객장비'), ('KAITS자산', 'KAITS자산')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='snmp',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('사용', '사용'), ('미사용', '미사용')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='snmp_sub',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='sys_log',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('사용', '사용'), ('미사용', '미사용')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='virus',
            name='contract',
            field=models.CharField(blank=True, choices=[('', '선택하세요'), ('1년 약정', '1년 약정'), ('2년 약정', '2년 약정'), ('3년 약정', '3년 약정'), ('4년 약정', '4년 약정'), ('5년 약정', '5년 약정')], max_length=50, null=True),
        ),
    ]
