# Generated by Django 2.1 on 2019-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191010_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='overseas_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(choices=[('', '선택하세요'), ('국내', '국내'), ('국외', '국외')], max_length=20),
        ),
    ]
