# Generated by Django 2.1 on 2019-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191010_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
