# Generated by Django 2.1 on 2019-10-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_email_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_password',
        ),
    ]
