# Generated by Django 2.1 on 2019-10-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sendemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SendEmail'),
        ),
    ]
